language: python
python:
  - '3.7'

env:
  global:
    - secure: Z+ZEhpX2x5/TOsjW1iXgUgsNitNgwVl16z/QL7e1rZey/1MKojyqT+Ju95LSEXcQfyKEOxsLwGI9uzyBb6ABj8X09Uz9rgJ2TU8GA/C6wGwyMS5ET3Fl/lJr68IDHa6Gf6VCPtXn1NxPpB2xJ5JdibEVyVhg9k9ChJAb49qM9om3r7npdKM9K8kyMvxhya2Y4lcxkCGnSw1oPr/moQS0yhL6yK3G8C0NAaGxCKa3PqutJp3GSORiySBaFvpEeC2oQ5a4vHY6gSqfhNQXgxy3rpxiZErPMmTPrq1kR2P+5v5UR70LFJRwWpeKAPnxeQSzCl1sFP8gQOz7ZngmnrI0oZ94sX41FlADQcI06LCW+hhAZs2WkXSPWifoBu8VdIAlzuy4AZYlIjRxTSwmXkzQ0StXlkmKmG4Xyh+eLxNz/wTmZDKFE4nYbFbSIxWqHROEsCqBl9Ogn7DXapyEX6iBhIMc8b7l48TPi+YOqTDy3u4JdpF46dkpRU27dUyrZDG4uFJYiO9fMj5Vp3MnNXhATFGMotSnFAIEvuyX/G9Jz9Sa/LrT711oPHayMxhU/RkHOe73W+4lXgx5sPWrVJxsxyr25M+qrjwJEc7QbbOV+CVszzvztm8+HLsjkP7p9tVzs1LOaJGRNC0cPZkbF1oEwTeT5oqjKp06Bv9o4V08ckA=

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential wget
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - "cd ta-lib/ && ./configure --prefix=/usr LDFLAGS="-lm" && make && sudo make install && cd .. && rm -r ta-lib"
  - python -m pip install poetry
  - poetry install

script:
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=.
  - poetry run tox -v

after_success:
  - poetry run coveralls
